defaults:
        - run: slurm
        - model: dntm_mnist
        - data: mnist
        - train: mnist_dntm
        - override hydra/hydra_logging: none
        - override hydra/job_logging: custom
        - _self_

hydra:
  run:
    dir: ../hydra/${hydra.job.name}/${now:%Y-%B-%d_%H-%M-%S}

