codename: default_local
cudnn: true
detect_anomaly: false
deterministic: false
device: cpu
loglevel: INFO
pin_memory: true
project_path: "/media/shift97/MyPassport/Flavio/repos/seq-mnist"
seed: 2147483647
use_amp: false
wandb_mode: online